version: '3.8'

services:
  db:
    image: postgres:14.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
#      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: school